import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const report = {
    timestamp: new Date().toISOString(),
    violations: [],
    security_perimeter: [],
    api_map: {},
    audit_passed: true
};

// 🚩 High-Risk Patterns
const VIOLATIONS = [
    { regex: /localStorage\.setItem\(['"](key|secret|token|auth|id|private|identity)/i, msg: 'Sensitive data stored in localStorage' },
    { regex: /console\.log\(.*(key|secret|token|private|password|auth|cipher)/i, msg: 'Potential sensitive data leak in console.log' },
    { regex: /fetch\(.*['"]http:\/\/.*['"]/i, msg: 'Insecure HTTP call detected (Use HTTPS/WSS)' },
    { regex: /Math\.random\(\)/i, msg: 'Weak PRNG detected (Use sodium.randombytes_buf)' }
];

function scanFiles(dir) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            if (file !== 'node_modules' && file !== '.git' && file !== 'pb_data') {
                scanFiles(fullPath);
            }
        } else if (file.endsWith('.js') || file.endsWith('.html')) {
            analyzeFile(fullPath);
        }
    }
}

function analyzeFile(filePath) {
    const content = fs.readFileSync(filePath, 'utf8');
    const relativePath = path.relative(rootDir, filePath);

    // 1. Compliance Audit
    const lines = content.split('\n');
    lines.forEach((line, index) => {
        VIOLATIONS.forEach(v => {
            if (v.regex.test(line)) {
                report.violations.push({ 
                    file: relativePath, 
                    message: `${v.msg} (Line ${index + 1}: "${line.trim()}")` 
                });
                report.audit_passed = false;
            }
        });
    });

    // 2. Security Perimeter
    if (content.includes('sodium') || content.includes('crypto')) {
        const cryptoUsage = (content.match(/sodium\.\w+/g) || []);
        report.security_perimeter.push({
            file: relativePath,
            features: [...new Set(cryptoUsage)],
            vault: content.includes('indexedDB')
        });
    }

    // 3. API Mapping
    const apiCalls = (content.match(/API\.\w+\(/g) || []);
    if (apiCalls.length > 0) {
        report.api_map[relativePath] = [...new Set(apiCalls.map(c => c.replace('API.', '').replace('(', '')))];
    }
}

console.log('🛡️  Running Zero-Knowledge Compliance Audit...');
scanFiles(rootDir);

const complianceDoc = `
# 🏁 Zero-Knowledge Compliance Status
Last Audit: ${report.timestamp}
Status: ${report.audit_passed ? '✅ PASSED' : '❌ FAILED'}

## 🚩 Compliance Violations
${report.violations.length > 0 
    ? report.violations.map(v => `- [ ] **${v.file}**: ${v.message}`).join('\n') 
    : 'No critical violations found. Codebase adheres to ZK security standards.'}

## 🔍 Security Perimeter Analysis
${report.security_perimeter.map(p => `
### ${p.file}
- **Primitives**: ${p.features.join(', ') || 'None'}
- **Vault Integrity**: ${p.vault ? '✅ Valid (IndexedDB)' : '❌ Not Found'}
`).join('')}

## 📡 Backend Dependency Graph
${Object.entries(report.api_map).map(([file, calls]) => `- **${file}** -> [${calls.join(', ')}]`).join('\n')}

---
*Note: This document is automatically generated by scripts/deep-insight.js. Do not edit manually.*
`;

fs.writeFileSync(path.join(rootDir, 'docs', 'COMPLIANCE.md'), complianceDoc);

if (!report.audit_passed) {
    console.error('\n❌ COMPLIANCE AUDIT FAILED. See docs/COMPLIANCE.md for details.');
    process.exit(1);
} else {
    console.log('\n✅ COMPLIANCE AUDIT PASSED.');
    process.exit(0);
}
